### ISSUE TITLE
Implement level selection

### ISSUE THREAD

**Issue by kuosandys** [ThePokeu/EnChord#32]
Players should be able to select a level other than "Easy". Some ideas:

Harder:
- playing the tones at the same time
- limiting number of times they can replay the tones

Easier:
- give chances to use a "hint" function - e.g. to play the tones between the tones in a scale
- play tones only in an upward direction for easier levels (currently it plays sometimes in a downward direction)

**Comment by eyeri91** [comment]
I reopened this issue as I only worked on the `Easy` level feature. I will continue working on the `Intermediate` and `Hard` levels and eventually close it. 😄
