### ISSUE TITLE
Rename the project

### ISSUE THREAD

**Issue by kuosandys** [ThePokeu/EnChord#40]
We had some good discussions recently about properly naming the project. Once we finalize our decision, we should update this info in various places:

- [x] repository name
- [x] title displayed in README
- [x] `name` field in `package.json`
- [x] `<title />` in `dist/index.html`
- [x] deployed website name

Ideas we had for names:
- encore
- enchord (for the pun lol)
- chimes
- ???

**Comment by eyeri91** [comment]
Oh Thank you for organizing and writing down the ideas! I did in my Obsidian account but then never shared lol (How selfish)

**Comment by eyeri91** [comment]
I think `EnChord` is a good name what do you think? Then I actually like all of them haha `Chimes` is cute too. Let me know what you think.

**Comment by kuosandys** [comment]
Let's go with `EnChord` 👍

**Comment by eyeri91** [comment]
We've got an issue here 😓 . `The Forks` or even `The Fork` is not available to change the organization name... I guess somebody else is using it.

**Comment by kuosandys** [comment]
ahhh all the good names are taken. `The Pokeus` could work, but I would pronounce it like "poke-us" or "po-kay-us" if I just saw it 😅 

What about just `pokeu`? I don't know what's the plural form of the word in Korean (for "forks") but I would pronounce `pokeu` like "pokü" which is slightly closer to how it's supposed to be pronounced?

(Stupid suggestion: `pokeupokeu` and with each new team member we add another `pokeu` 🤣 )

**Comment by eyeri91** [comment]
Funny enough, we don't really use the plural form of nouns or if we don't, we just add a number in front of it. So `The Pokeu` works perfectly fine. So we go with `Pokeu`!

And I love your suggestion 🤣 🤣 🤣  It will become `The infinity of Pokeu` in the end hahaha
